#!/bin/sh

. $XDG_CONFIG_HOME/river/config
. $XDG_CONFIG_HOME/river/autostart
. $XDG_CONFIG_HOME/river/mappings
. $XDG_CONFIG_HOME/river/rules

# useful for debugging
# notify-send "River" "River has been (re)started"
