#!/bin/sh

#### Autostart ####
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
feh --no-fehbg --bg-fill $HOME/Pictures/wallpapers/arch.png &
easyeffects --gapplication-service &
# picom &
dunst &
flameshot &

#### BSPWM Monitors ####
bspc monitor -d 1 2 3 4 5 6 7 8 9

#### BSPWM Config ####
bspc config border_width         0 
bspc config window_gap           12
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config pointer_modifier     mod4
bspc config pointer_action1      move
bspc config pointer_action2      resize_corner
bspc config pointer_action3      resize_side

#### BSPWM Rules ####
# bspc rule -a Gimp desktop='^8' state=floating follow=on

#### Steam Rules ####
# Does not work for native games.
#games="$(ls $XDG_DATA_HOME/Steam/steamapps/appmanifest_*.acf | sed 's/[^0-9]*//g')"
#for game in $games; do
#  bspc rule -a steam_app_$game desktop=^8 state=fullscreen follow=on
#done

#### BSPWM External Rules ####
bspc config external_rules_command $HOME/.config/bspwm/scripts/steam_games.sh
