[colors.bright]
black = "0x928374"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe3a84e"

[colors.normal]
black = "0x665c54"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe78a4e"

[colors.primary]
background = "0x1d2021"
foreground = "0xd4be98"

[font]
size = 11

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Medium"

#[schemes.everforest_dark_hard.bright]
#black = "#4b565c"
#blue = "#7fbbb3"
#cyan = "#83c092"
#green = "#a7c080"
#magenta = "#d699b6"
#red = "#e67e80"
#white = "#d3c6aa"
#yellow = "#dbbc7f"

#[schemes.everforest_dark_hard.normal]
#black = "#4b565c"
#blue = "#7fbbb3"
#cyan = "#83c092"
#green = "#a7c080"
#magenta = "#d699b6"
#red = "#e67e80"
#white = "#d3c6aa"
#yellow = "#dbbc7f"
#
#[schemes.everforest_dark_hard.primary]
#background = "#2b3339"
#foreground = "#d3c6aa"
#
#[schemes.gruvbox_material.bright]
#black = "0x928374"
#blue = "0x7daea3"
#cyan = "0x89b482"
#green = "0xa9b665"
#magenta = "0xd3869b"
#red = "0xea6962"
#white = "0xdfbf8e"
#yellow = "0xe3a84e"
#
#[schemes.gruvbox_material.normal]
#black = "0x665c54"
#blue = "0x7daea3"
#cyan = "0x89b482"
#green = "0xa9b665"
#magenta = "0xd3869b"
#red = "0xea6962"
#white = "0xdfbf8e"
#yellow = "0xe78a4e"
#
#[schemes.gruvbox_material.primary]
#background = "0x1d2021"
#foreground = "0xd4be98"

[window]
dynamic_title = true

[window.padding]
x = 3
y = 3
