theme = "everforest_dark"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
h = "insert_mode"
H = "prepend_to_line"
I = "no_op"
i = "move_line_up"
k = "move_line_down"
j = "move_char_left"
l = "move_char_right"
